M48
; DRILL file {KiCad 9.0.1} date 2025-04-15T18:06:26+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-15T18:06:26+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X116.245Y-51.96
X116.245Y-98.91
X140.755Y-51.96
X140.755Y-98.91
M30
